INSERT INTO VOTERS (VOTER_ID, FIRST_NAME, LAST_NAME, FATHER_NAME, GENDER, DATE_OF_BIRTH, DOOR_NO, STREET, LOCALITY, POST, TALUK, DISTRICT, STATE, COUNTRY, ZIP_CODE)
VALUES ('ABC001','Manjunath','HM','Munikrishnappa','MALE','10/02/1992','#001','1st Street','Hireballa','Jangamakote', 'Sidlagatta','Chikkaballapur', 'Karnataka', 'India', '562012');

INSERT INTO VOTERS (VOTER_ID, FIRST_NAME, LAST_NAME, FATHER_NAME, GENDER, DATE_OF_BIRTH, DOOR_NO, STREET, LOCALITY, POST, TALUK, DISTRICT, STATE, COUNTRY, ZIP_CODE)
VALUES ('ABC002','Manoj','HM','Munikrishnappa','MALE','27/10/1996','#001','1st Street','Hireballa','Jangamakote', 'Sidlagatta','Chikkaballapur', 'Karnataka', 'India', '562012');

INSERT INTO VOTERS (VOTER_ID, FIRST_NAME, LAST_NAME, FATHER_NAME, GENDER, DATE_OF_BIRTH, DOOR_NO, STREET, LOCALITY, POST, TALUK, DISTRICT, STATE, COUNTRY, ZIP_CODE)
VALUES ('ABC003','Kumari','V','V','FEMALE','00/00/0000','#001','1st Street','Chintamani','Chintamani', 'Chintamani','Chikkaballapur', 'Karnataka', 'India', '562013');

INSERT INTO VOTERS (VOTER_ID, FIRST_NAME, LAST_NAME, FATHER_NAME,HUSBAND_NAME, GENDER, DATE_OF_BIRTH, DOOR_NO, STREET, LOCALITY, POST, TALUK, DISTRICT, STATE, COUNTRY, ZIP_CODE)
VALUES ('ABC004','Shubha','GL','L','XXXX','FEMALE','00/00/0000','#001','1st Street','Chitradurga','Chitradurga', 'Chitradurga','Chitradurga', 'Karnataka', 'India', '56xxxx');

INSERT INTO VOTERS (VOTER_ID, FIRST_NAME, LAST_NAME, FATHER_NAME, GENDER, DATE_OF_BIRTH, DOOR_NO, STREET, LOCALITY, POST, TALUK, DISTRICT, STATE, COUNTRY, ZIP_CODE)
VALUES ('ABC005','Abhilash','XX','XXXXXXXXXX','MALE','xx/xx/xxxx','#001','1st Street','Mysuru','Mysuru', 'Mysuru','Mysuru', 'Karnataka', 'India', '56xxxx');